# Generated by Django 5.2.14 on 2026-05-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_add_monitoringuser'),
        ('monitoring', '0002_monitoringuser'),
    ]

    operations = [
    ]
